- name: Sediakan web server
  hosts: web
  become: true
  vars:
    docker_users: [ubuntu]
    aws_region: ap-southeast-1
  roles:
    - geerlingguy.docker
    - prometheus.prometheus.node_exporter
  tasks:
    - name: Pasang unzip
      apt:
        name: unzip
        state: present
        update_cache: yes

    - name: Muat turun pemasang AWS CLI v2
      get_url:
        url: https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip
        dest: /tmp/awscliv2.zip

    - name: Nyahzip pemasang AWS CLI v2
      unarchive:
        src: /tmp/awscliv2.zip
        dest: /tmp
        remote_src: yes

    - name: Pasang AWS CLI v2
      command: /tmp/aws/install
      args:
        creates: /usr/local/bin/aws

    - name: Log masuk ke ECR
      shell: >
        aws ecr get-login-password --region {{ aws_region }}
        | docker login --username AWS --password-stdin {{ ecr_repository_url.split('/')[0] }}
      changed_when: true

    - name: Tarik image aplikasi terkini
      command: docker pull {{ ecr_repository_url }}:latest
      changed_when: true

    - name: Hentikan container lama (jika ada)
      command: docker rm -f ship
      failed_when: false
      changed_when: false

    - name: Naikkan container aplikasi
      command: >
        docker run -d --name ship --restart unless-stopped
        -p 80:80 {{ ecr_repository_url }}:latest
      changed_when: true
